# Generated by Django 3.2.10 on 2021-12-14 19:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default_name', max_length=200)),
                ('overdraft', models.BooleanField(default=False)),
                ('current_balance', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_transaction', models.PositiveBigIntegerField()),
                ('donor_uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor_uid', to='service_transactions.accounts')),
                ('recipient_uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_uid', to='service_transactions.accounts')),
            ],
        ),
    ]
