version: '3.7'
services:
  web:
    build: ../app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ../app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
  db:
    image: postgres
    env_file:
      - .env.dev
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
